#Stage1: Copy requirements and duild. 
FROM python3.11 AS builder

WORKDIR /app

# update sustem requirements
RUN apt-get update && apt-get install -y --no-install-recommends \
    gcc \
    libc6-dev \
    && rm -rf /var/lib/apt/lists/*

COPY requirements.txt .

RUN pip install --upgrade pip && \
    pip install --user --no-cache-dir -r requirements.txt

#Stage2: Python runtime.
FROM python:3.11-slim

WORKDIR /app

COPY --from=builder /root/.local /root/.local
COPY . .

# Update PATH
ENV PATH=/root/.local/bin:$PATH

# Create not root user.
RUN useradd -m appuser && chown -R appuser /app
USER appuser


CMD ["python", "main.py"]